### ISSUE TITLE
[Bug] Korean font is broken (kr_v1121, mc1.19.4)

### ISSUE THREAD

**Issue by shihyeon** [YutaYamamoto212/ModernFontPack#2] opened 2023-06-08 11:05 UTC
### Description of the Bug

It was found that the font was broken when color and light effects were added to the sign written in Korean font.

### Steps to Reproduce

```bash
1. Apply the font.
2. Write in Korean font on the sign.
3. Apply a glow effect.
4. When the light effect is given, the bold part is broken.
```

### Expected Behavior

Please handle the bold part where the glow effect is given naturally.

### Actual Behavior

It is the same as the above.

### Modern Font Pack Version

v1021

### What is the game version you are playing?

java ed. mc1.19.4

### What is the system of the device you are using?

Windows

**Comment by YutaYamamoto212** [comment] 2023-06-09 01:25
Thanks for your report. However, this issue is caused by a limitation of the game itself, and I cannot control or fix it. Related issues are documented in the Frequently Asked Question, which can be found on CurseForge or Modrinth's pages. The title of the question is "I'm using a glow ink sac on a sign and I'm finding the effect is getting weird. What should I do?"
Therefore, this issue will be closed as **Won't Fix**.

**Closed as not planned by YutaYamamoto212** 2023-06-09 01:25 UTC
Labels: Bug, Won't Fix, Java Edition

**Comment by Artoria2e5** [comment] 2026-02-21 08:19
Ordinary, non-glowing bold also appear as doubling/overstrike (`§oaaa§lppp§r§lbbb`), which is less than ideal (1.21.1):

<img width="296" height="76" alt="Image" src="https://github.com/user-attachments/assets/e92f627b-7215-4c94-ac4e-9967ef9cd735" />

That said, this is in the FAQ, and I should try Caxton.
